# Generated by Django 6.0.1 on 2026-01-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Изображение')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('game', models.CharField(choices=[('CS2', 'Counter-Strike 2'), ('Dota2', 'Dota 2'), ('Valorant', 'Valorant'), ('LoL', 'League of Legends'), ('Overwatch2', 'Overwatch 2'), ('Apex', 'Apex Legends'), ('Fortnite', 'Fortnite'), ('Other', 'Другое')], max_length=20, verbose_name='Игра')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
    ]
